pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id("co.elastic.otel.android.agent") version "$agent_version"
        id("co.elastic.otel.android.instrumentation.okhttp") version "${agent_version}"
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}
rootProject.name = "OpBeans demo"
include ':app'
