plugins {
    alias(libs.plugins.android.app)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.spotless)
    alias(libs.plugins.firebase.appDistribution)
    id 'co.elastic.otel.android.agent' version "${agent_version}"
    id("co.elastic.otel.android.instrumentation.okhttp") version "${agent_version}"
}

android {
    compileSdkVersion 36
    namespace "co.elastic.apm.opbeans"
    buildFeatures.buildConfig true

    defaultConfig {
        applicationId "co.elastic.apm.opbeans"
        minSdk 26
        versionCode 1
        versionName "1.0"

        buildConfigField "String", 'OPBEANS_URL', "\"${project.properties.getOrDefault("opbeans_endpoint", "http://10.0.2.2:3000")}\""
        buildConfigField "String", 'OPBEANS_AUTH_TOKEN', "\"${project.properties.getOrDefault("opbeans_auth_token", "")}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            firebaseAppDistribution {
                appId = System.getenv("OPBEANS_APP_ID")
                artifactType = "APK"
                groups = "elastic-testers"
                releaseNotes = project.properties.getOrDefault("firebase_release_notes", "None")
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    testOptions {
        animationsDisabled = true
    }
}

dependencies {
    implementation(libs.android.material)
    implementation(libs.android.fragment)
    implementation(libs.hilt)
    implementation(libs.retrofit)
    implementation(libs.retrofit.gson)
    implementation(libs.glide)
    implementation(libs.glide.okhttp)
    implementation(libs.android.room)
    implementation(libs.android.room.ktx)
    implementation(libs.android.swiperefresh)
    implementation(libs.android.paging)
    ksp(libs.android.room.compiler)
    ksp(libs.glide.compiler)
    ksp(libs.hilt.compiler)
    testImplementation(libs.junit)
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso_version"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$espresso_version"
}

spotless {
    java {
        target 'src/*/java/**/*.java'
        licenseHeader getSourceHeader()
    }
    kotlin {
        target 'src/*/java/**/*.kt'
        licenseHeader getSourceHeader()
    }
}

private String getSourceHeader() {
    '/* \n' +
            'Licensed to Elasticsearch B.V. under one or more contributor\n' +
            'license agreements. See the NOTICE file distributed with\n' +
            'this work for additional information regarding copyright\n' +
            'ownership. Elasticsearch B.V. licenses this file to you under\n' +
            'the Apache License, Version 2.0 (the "License"); you may\n' +
            'not use this file except in compliance with the License.\n' +
            'You may obtain a copy of the License at\n' +
            '\n' +
            '  http://www.apache.org/licenses/LICENSE-2.0\n' +
            '\n' +
            'Unless required by applicable law or agreed to in writing,\n' +
            'software distributed under the License is distributed on an\n' +
            '"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n' +
            'KIND, either express or implied.  See the License for the\n' +
            'specific language governing permissions and limitations\n' +
            'under the License. \n' +
            '*/'
}
